copy /Y D:\Links\ahk\xfold\xfold-cmd.ahk .\
copy /Y D:\Links\regjump.bat .\
copy /Y D:\Links\msg-welink.ahk .\
copy /Y D:\Links\work-x1\mail-cmd.ahk .\
copy /Y D:\Links\filelocator\locator-cmd.ahk .\
copy /Y D:\Links\everything\findit.ahk .\
copy /Y D:\Links\everything\everything-cmds.bat .\
copy /Y D:\Links\everything\everything-cmd-list.csv .\
copy /Y D:\Links\everything\everything-cmd.ahk .\
copy /Y D:\Links\evernote\evernote-cmds.bat .\
copy /Y D:\Links\evernote\evernote-cmd-list.csv .\
copy /Y D:\Links\evernote\evernote-cmd.ahk .\
copy /Y D:\Links\collect-cmd-v2.bat .\
copy /Y D:\Links\ahk-cmd.ahk .\
